config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→自分がフォローしている人

  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @new_book = Book.new
    @books = Book.all
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @book_user = @book.user
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@new_book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new
    favorite.book_id = book.id
    favorite.save
    redirect_to book_path(book.id)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book.id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    # followはuserモデルで定義
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    # unfollowはuserモデルで定義
    redirect_to request.referer
  end

  def followings
     user = User.find(params[:user_id])
     @users = user.followings
  end

  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = User.find(params[:id])
  @books = @user.books.all
  @new_book = Book.new
end

def index
  @new_book = Book.new
  @users = User.all
  @user = current_user
end

def edit
  @user = User.find(params[:id])
  if @user != current_user
    redirect_to user_path(current_user)
  end
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    @users = User.all
    render :edit
  end
end

private
def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <!--User info-->
  <div class="profile-container">
    <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>フォロー数</th>
          <th><%= user.followings.count %></th>
        </tr>
        <tr>
          <th>フォロワー数</th>
          <th><%= user.followers.count %></th>
        </tr>
      </table>
      <div class="row">
          <%= link_to '', edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
  </div>

  <!--form-->
  <h2 class="mt-3">New book</h2>
    <%= form_with model: new_book, local:true do |f| %>
      <div class="form-group">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
      </div>
      <div class="form-group">
      <%= f.label :opinion %><br />
      <%= f.text_area :body %>
      </div>
      <div class="form-group">
      <%= f.submit'Create Book', class: 'btn btn-success'%>
      </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
        <div id="error-massage">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
              <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
          <% end %>
        </div>

        <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: 'form-controll' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %><br />
          <%= f.text_area :body, class: 'form-controll' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

    <div id="error-massage">
      <% if @new_book.errors.any? %>
        <h3><%= @new_book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @new_book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

  <div class="row">

  <%= render 'books/list', user: @user, new_book: @new_book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render 'books/list', user: @book_user, new_book: @new_book %>

    <div class="col-md-8 offset-md-1">
      <!--book detail-->
      <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag @book_user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %><br />
                <%= link_to @book_user.name, user_path(@book_user) %>
              </td>
              <td>
                <%= link_to @book.title, book_path %>
              </td>
              <td>
                <%= @book.body %>
              </td>

              <% if @book.favorited_by?(current_user) %>
                <td><%= link_to "♥", book_favorite_path(@book), method: :delete %></td>
              <% else %>
                <td><%= link_to "♡", book_favorites_path(@book), method: :post %></td>
              <% end %>

              <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success' %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-sm btn-danger', "data-confirm" => "本当に消しますか？" %>
              </td>
              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">

    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      Bookers!
    </h1>

  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>
        welcome to <i class="fas fa-book"></i>Bookers !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers,</strong>
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign-in' %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign-up' %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100">
  <header>
    <div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
          <a class="navbar-brand" href="https://2f50326f9d554a51b3db642e615c7a2b.vfs.cloud9.us-east-1.amazonaws.com/">
            <span>Bookers</span>
          </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to ' Home', user_path(current_user.id), class: 'nav-link text-light fas fa-home' %>
              </li>
              <li class="nav-item">
                </i><%= link_to ' Users', users_path, class: 'nav-link text-light fas fa-users' %>
              </li>
              <li class="nav-item">
                 <%= link_to ' Books', books_path, class: 'nav-link text-light fas fa-book-open' %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'nav-link text-light fas fa-sign-out-alt' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to ' Home', root_path, class: 'nav-link text-light fas fa-home' %>
              </li>
              <li class="nav-item">
                <%= link_to ' About', home_about_path, class: 'nav-link text-light fas fa-link' %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: 'nav-link text-light fas fa-user-plus' %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: 'nav-link text-light fas fa-sign-in-alt' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: key) %>
    <% end %>

    <div id="notice">
    <%= yield %>
    </div>
  </main>

</body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          CopyRight Infratop.inc
        </div>
      </div>
    </div>
  </footer>

</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
        <div id="error-massage">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
          <% end %>
        </div>

        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :name %><br />
            <%= f.text_field :name, class: 'form-controll' %>
          </div>
          <div class="form-group">
            <%= f.label :Image %><br />
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %><br />
            <%= f.text_area :introduction, class: 'form-controll' %>
          </div>
            <%= f.submit "Update User", class: 'form-group btn btn-secondary' %>
        <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'books/list', user: @user, new_book: @new_book %>

    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>フォロー数: <%= user.followings.count %></td>
              <td>フォロワー数: <%= user.followers.count %></td>
              <td>
                <% if current_user != user %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to'Show', user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'books/list', user: @user, new_book: @new_book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                  </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>